openapi:
  auth:
    url: http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19SidoInfStateJson
    key: L54KA%2BbfldcX5GKUxG6cB16LffsXzBZ8IuZEfgx9cWKuiApTFC%2B3GOsGusJZv1FZq7fpQqUmhtUh0VK9eWHD3g%3D%3D
slack:
  channel:
    url: ENC(JfTBjrNLm+ZRZ+arrxi+nlRwil6+4L94yZLIDZCEslC4okdLZ+2ykQvmd4/l13gy3N2X1X9VLXwyBoEGnnytzCaXY6wIO6xMvHrihT7kjzloV3kcq/o+nZxe+0yO4cpH)
redis:
  patients:
    today:
      key: today
    latest:
      key: latest