openapi:
  auth:
    url: http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19SidoInfStateJson
    key: L54KA%2BbfldcX5GKUxG6cB16LffsXzBZ8IuZEfgx9cWKuiApTFC%2B3GOsGusJZv1FZq7fpQqUmhtUh0VK9eWHD3g%3D%3D
slack:
  channel:
    url: https://hooks.slack.com/services/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

redis:
  patients:
    today:
      key: today
    latest:
      key: latest